name: Build Opus DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install nasm -y
        choco install cmake -y
        choco install mingw -y

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        mingw32-make

    - name: Upload DLL as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: opus-dll
        path: build/**/opus.dll

    - name: Upload DLL to GitHub Release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.sha }}
        tag_name: build-${{ github.run_number }}
        files: build/**/opus.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
